{
  apl: [ 'dyalog', 'apl' ],
  asciiarmor: [ 'asc', 'pgp', 'sig' ],
  'asn.1': [ 'asn', 'asn1' ],
  asterisk: undefined,
  brainfuck: [ 'b', 'bf' ],
  clike: [
    'c',    'h',     'ino',
    'cpp',  'c++',   'cc',
    'cxx',  'hpp',   'h++',
    'hh',   'hxx',   'cs',
    'java', 'kt',    'm',
    'mm',   'scala', 'nut'
  ],
  cobol: [ 'cob', 'cpy', 'cbl' ],
  clojure: [ 'clj', 'cljc', 'cljx', 'cljs', 'edn' ],
  css: [ 'gss', 'css', 'less', 'scss' ],
  cmake: [ 'cmake', 'cmake.in' ],
  coffeescript: [ 'coffee' ],
  commonlisp: [ 'cl', 'lisp', 'el' ],
  cypher: [ 'cyp', 'cypher' ],
  python: [
    'pyx', 'pxd',
    'pxi', 'BUILD',
    'bzl', 'py',
    'pyw'
  ],
  crystal: [ 'cr' ],
  sql: [
    'cql',     undefined,
    undefined, undefined,
    undefined, 'pls',
    undefined, 'sql',
    undefined
  ],
  d: [ 'd' ],
  dart: [ 'dart' ],
  diff: [ 'diff', 'patch' ],
  django: undefined,
  dockerfile: undefined,
  dtd: [ 'dtd' ],
  dylan: [ 'dylan', 'dyl', 'intr' ],
  ebnf: undefined,
  ecl: [ 'ecl' ],
  eiffel: [ 'e' ],
  elm: [ 'elm' ],
  htmlembedded: [ 'ejs', 'erb', 'aspx', 'jsp' ],
  erlang: [ 'erl' ],
  factor: [ 'factor' ],
  fcl: undefined,
  forth: [ 'forth', 'fth', '4th' ],
  fortran: [ 'f', 'for', 'f77', 'f90', 'f95' ],
  mllike: [
    'fs',        'ml',
    'mli',       'mll',
    'mly',       'sml',
    'sig',       'fun',
    'smackspec'
  ],
  gas: [ 's' ],
  gherkin: [ 'feature' ],
  gfm: undefined,
  go: [ 'go' ],
  groovy: [ 'groovy', 'gradle' ],
  haml: [ 'haml' ],
  haskell: [ 'hs' ],
  'haskell-literate': [ 'lhs' ],
  haxe: [ 'hx', 'hxml' ],
  htmlmixed: [ 'html', 'htm', 'handlebars', 'hbs' ],
  http: undefined,
  idl: [ 'pro' ],
  pug: [ 'jade', 'pug' ],
  javascript: [ 'js', 'json', 'map', 'jsonld', 'ts' ],
  jsx: [ 'jsx', 'tsx' ],
  jinja2: [ 'j2', 'jinja', 'jinja2' ],
  julia: [ 'jl' ],
  livescript: [ 'ls' ],
  lua: [ 'lua' ],
  markdown: [ 'markdown', 'md', 'mkd' ],
  mirc: undefined,
  mathematica: [ 'm', 'nb', 'wl', 'wls' ],
  modelica: [ 'mo' ],
  mumps: [ 'mps' ],
  mbox: [ 'mbox' ],
  nginx: undefined,
  nsis: [ 'nsh', 'nsi' ],
  ntriples: [ 'nt', 'nq' ],
  octave: [ 'm' ],
  oz: [ 'oz' ],
  pascal: [ 'p', 'pas' ],
  pegjs: [ 'jsonld' ],
  perl: [ 'pl', 'pm' ],
  php: [ 'php', 'php3', 'php4', 'php5', 'php7', 'phtml' ],
  pig: [ 'pig' ],
  null: [ 'txt', 'text', 'conf', 'def', 'list', 'log' ],
  powershell: [ 'ps1', 'psd1', 'psm1' ],
  properties: [ 'properties', 'ini', 'in' ],
  protobuf: [ 'proto' ],
  puppet: [ 'pp' ],
  q: [ 'q' ],
  r: [ 'r', 'R' ],
  rst: [ 'rst' ],
  rpm: [ undefined, 'spec' ],
  ruby: [ 'rb' ],
  rust: [ 'rs' ],
  sas: [ 'sas' ],
  sass: [ 'sass' ],
  scheme: [ 'scm', 'ss' ],
  shell: [ 'sh', 'ksh', 'bash' ],
  sieve: [ 'siv', 'sieve' ],
  slim: [ 'slim' ],
  smalltalk: [ 'st' ],
  smarty: [ 'tpl' ],
  solr: undefined,
  soy: [ 'soy' ],
  sparql: [ 'rq', 'sparql' ],
  spreadsheet: undefined,
  stylus: [ 'styl' ],
  swift: [ 'swift' ],
  stex: [ undefined, 'text', 'ltx', 'tex' ],
  verilog: [ 'v', 'sv', 'svh', 'v' ],
  tcl: [ 'tcl' ],
  textile: [ 'textile' ],
  tiddlywiki: undefined,
  tiki: undefined,
  toml: [ 'toml' ],
  tornado: undefined,
  troff: [
    '1', '2', '3',
    '4', '5', '6',
    '7', '8', '9'
  ],
  ttcn: [ 'ttcn', 'ttcn3', 'ttcnpp' ],
  'ttcn-cfg': [ 'cfg' ],
  turtle: [ 'ttl' ],
  twig: undefined,
  webidl: [ 'webidl' ],
  vb: [ 'vb' ],
  vbscript: [ 'vbs' ],
  velocity: [ 'vtl' ],
  vhdl: [ 'vhd', 'vhdl' ],
  vue: [ 'vue' ],
  xml: [ 'xml', 'xsl', 'xsd', 'svg' ],
  xquery: [ 'xy', 'xquery' ],
  yacas: [ 'ys' ],
  yaml: [ 'yaml', 'yml' ],
  z80: [ 'z80' ],
  mscgen: [ 'mscgen', 'mscin', 'msc', 'xu', 'msgenny' ],
  wast: [ 'wat', 'wast' ]
}
[Finished in 36ms]